### ISSUE TITLE
郭老师，在feature多模块中如何使用hilt？

### ISSUE THREAD

**Issue by chentl666** [guolindev/HiltSample#2]

**Comment by guolindev** [comment]
只要你的项目主模块使用了hilt，多模块中就也可以实现，而且用法一模一样，没有任何区别。但如果你的主模块没有使用hilt，那么其他的模块也就用不了了。

**Comment by chentl666** [comment]
https://developer.android.google.cn/training/dependency-injection/hilt-multi-module
貌似Hilt还不支持，只能用dagger，有点头疼！








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lin Guo"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 下午3:37
收件人: "guolindev/HiltSample"<HiltSample@noreply.github.com&gt;; 
抄送: "天伦之乐"<1228061920@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [guolindev/HiltSample] 郭老师，在feature多模块中如何使用hilt？ (#2)





 
只要你的项目主模块使用了hilt，多模块中就也可以实现，而且用法一模一样，没有任何区别。但如果你的主模块没有使用hilt，那么其他的模块也就用不了了。

**Comment by guolindev** [comment]
不知道是你具体什么需求，但如果这个文档上面的描述还满足不了你的使用场景的话，那就还是使用dagger吧。
